networks:
  custom:
    - name: katana
      chain_id: 747474
      ecosystem: ethereum

node:
  ethereum:
    mainnet:
      transaction_acceptance_timeout: 1800  # 30 minutes
      gas_limit:
        auto:
          multiplier: 2  # Multiply 2 times the result of eth_estimateGas
      uri: "${ETH_RPC_URL}"
      ws_uri: "${ETH_WS_URL}"
    katana:
      uri: "${KATANA_RPC_URL}"
      ws_uri: "${KATANA_WS_URL}"

  base:
    mainnet:
      uri: "${BASE_RPC_URL}"
      ws_uri: "${BASE_WS_URL}"

  arbitrum:
    mainnet:
      uri: "${ARB_RPC_URL}"
      ws_uri: "${ARB_WS_URL}"